apiVersion: v1
kind: Pod
metadata:
 name: liveness-pod-http
spec:
 containers:
 - name: nginx
   image: nginx:1.19.1
   command: ['sh','-c','while true; do sleep 3600; done']
   livenessProbe:
    httpGet:
     path: /
     port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
